# Generated by Django 3.2 on 2025-01-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
            ],
            options={
                'db_table': 'LR',
            },
        ),
        migrations.CreateModel(
            name='manage_users_model',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_Profile', models.FileField(upload_to='images/')),
                ('User_Email', models.EmailField(max_length=50)),
                ('User_Status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'manage_users',
            },
        ),
        migrations.CreateModel(
            name='NB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
            ],
            options={
                'db_table': 'NB',
            },
        ),
        migrations.CreateModel(
            name='SVM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('accuracy', models.FloatField(max_length=100)),
                ('precision', models.FloatField(max_length=100)),
                ('recall', models.FloatField(max_length=100)),
                ('f1_score', models.FloatField(max_length=100)),
            ],
            options={
                'db_table': 'SVM',
            },
        ),
    ]
